default:
  http_metas:
    content-type: text/html

  metas:
    title:        Админка
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    [bootstrap.js]

  has_layout:     on
  layout:         layout
