<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/01/03 13:33:17

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'sqlite:D:\\xampp\\htdocs\\sf_sandbox\\data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
