<?php
// auto-generated by sfRoutingConfigHandler
// date: 2014/01/03 13:33:18
return array(
'list_of_posts' => new sfRoute('/latest_posts', array (
  'module' => 'post',
  'action' => 'index',
), array (
), array (
)),
'post' => new sfRoute('/blog/:title', array (
  'module' => 'post',
  'action' => 'permalink',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'module' => 'main',
  'action' => 'index',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
