<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/12/28 05:58:56

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'sqlite:D:\\xampp\\htdocs\\sf_sandbox\\data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
