<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2013/12/28 06:05:50
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoPost/actions/actions.class.php');

