<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2013/12/28 06:06:35
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoComment/actions/actions.class.php');

